#!/usr/bin/env python3
"""Regenerate include/nr_bb/ldpc_bg_tables.hpp from vendored Sionna CSVs."""
from __future__ import annotations
import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "include" / "nr_bb" / "ldpc_bg_tables.hpp"


def parse(path: Path):
    rows = list(csv.reader(path.open(), delimiter=";"))
    edges = []
    r_ind = 0
    for row in rows[2:]:
        if row[0].strip() != "":
            r_ind = int(float(row[0]))
        c_ind = int(float(row[1]))
        shifts = []
        for i in range(8):
            v = row[2 + i].strip()
            shifts.append(int(float(v)) if v != "" else -1)
        edges.append((r_ind, c_ind, shifts))
    return edges


def emit_edges(name: str, edges) -> str:
    lines = [f"inline constexpr BgEdge {name}[] = {{"]
    for r, c, sh in edges:
        shs = ", ".join(str(x) for x in sh)
        lines.append(f"  {{{r}, {c}, {{{shs}}}}},")
    lines.append("};")
    lines.append(f"inline constexpr int {name}_COUNT = {len(edges)};")
    return "\n".join(lines)


def main() -> None:
    bg1 = parse(ROOT / "third_party/sionna_ldpc_codes/5G_bg1.csv")
    bg2 = parse(ROOT / "third_party/sionna_ldpc_codes/5G_bg2.csv")
    text = f"""#pragma once
/**
 * @file ldpc_bg_tables.hpp
 * @brief 5G NR LDPC base-graph shift tables (BG1/BG2, all i_LS).
 *
 * PROVENANCE:
 * - Tables transcribed from NVIDIA Sionna `5G_bg1.csv` / `5G_bg2.csv`
 *   (Apache-2.0), which encode 3GPP TS 38.212 Tables 5.3.2-2 / 5.3.2-3.
 * - Vendored CSV + NOTICE: third_party/sionna_ldpc_codes/
 * - NO proprietary NVIDIA Aerial / cuBB source.
 * - Auto-generated by scripts/generate_ldpc_bg_tables.py — do not hand-edit.
 */
#include <cstdint>

namespace nr_bb {{
namespace ldpc_tables {{

struct BgEdge {{
  int row;
  int col;
  int shift[8];
}};

{emit_edges("BG1_EDGES", bg1)}

{emit_edges("BG2_EDGES", bg2)}

inline constexpr int BG1_MB = 46;
inline constexpr int BG1_NB = 68;
inline constexpr int BG1_KB = 22;
inline constexpr int BG2_MB = 42;
inline constexpr int BG2_NB = 52;
inline constexpr int BG2_KB = 10;

}}  // namespace ldpc_tables
}}  // namespace nr_bb
"""
    OUT.write_text(text)
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
